- name: 'Add repo PHP 5.6 (Ondřej Surý PPA)'
  apt_repository: repo='ppa:ondrej/php5-5.6'

- name: PHP + libraries installed
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-common
    - php5-fpm
    - php5-dev
    - php5-cli
    - php5-intl
    - php5-json
    - php5-curl
    - php5-mcrypt
    - php5-gd
    - php5-xdebug
    - php5-apcu
    - php5-pgsql
    - php-pear
  tags: php

- name: enable php modules
  shell: php5enmod {{ item }}
  with_items:
    - mcrypt
  notify:
    - restart phpfpm

- name: configure PHP settings
  template: src=php.ini dest=/etc/php5/fpm/conf.d/custom.ini  
  notify:
    - restart phpfpm
  tags: php

- name: APC enabled CLI
  shell: echo "apc.enable_cli=1" >> /etc/php5/mods-available/apcu.ini
  notify:
    - restart phpfpm
  tags: php

- name: configure PHP-FPM Pool settings
  template: src=www-pool.j2 dest=/etc/php5/fpm/pool.d/www.conf
  notify:
    - restart phpfpm
  tags: php

- name: chown PHP-FPM sessions dir
  shell: chown {{ username }}:{{ username }} /var/lib/php5 -Rf
  tags: php
